### ISSUE TITLE
可以实现封装的泛型类吗？

### ISSUE THREAD

**Issue by xiangxm** [zyyoona7/WheelPicker#1]
比如城市信息 有个id ,name 等字段封装成了Bean,  使用wheelpicker 可以直接使用，有相关回调回来取需要显示哪个字段。

**Comment by zyyoona7** [comment]
可以的，我的 README 竟然漏了这一点，和 WheelView 同级包下有一个 IWheelEntity 接口，实现它以后在 getWheelText() 方法返回 WheelView 中展示的文字即可。

现在功能正在逐步完善中，正在基于 WheelView 封装各种选择器，敬请期待~之后更新更加详细的文档

**Comment by xiangxm** [comment]
谢谢分享。 辛苦了~

**Comment by zyyoona7** [comment]
@xiangxm 文档和 Demo 都已经更新，欢迎下载尝鲜~

**Comment by xiangxm** [comment]
谢谢
