### ISSUE TITLE
能否添加一个让选中的条目字体加粗

### ISSUE THREAD

**Issue by ZXingYe** [zyyoona7/WheelPicker#12]
能否添加一个让选中的条目字体加粗，刚好遇到这样的需求。
辛苦了。。。。。

**Comment by zyyoona7** [comment]
只是选中字体吗？这个和单独设置选中大小的功能类似~最近工作有点忙，新功能可能会慢一些。

**Comment by zyyoona7** [comment]
1.0.6 版本已加入这个功能，欢迎尝试~
