### ISSUE TITLE
设置字体后文字就不居中了

### ISSUE THREAD

**Issue by jxoday** [zyyoona7/WheelPicker#13]
//字体信息
        Typeface typeface = FontCache.getTypeface("Digital-7Mono.ttf");
        wheelSecond.setTypeface(typeface);
wheelSecond.setTextAlign(WheelView.TEXT_ALIGN_CENTER);

**Comment by zyyoona7** [comment]
感谢反馈，**Digital-7Mono.ttf** 这个字体确实会导致不居中，但是我 Demo 里面又加入了苹方字体就是正常的，初步怀疑是字体原因，明天我再具体排查一下~

**Comment by jxoday** [comment]
> 感谢反馈，**Digital-7Mono.ttf**这个字体确实会导致不居中，但是我Demo里面又加入了苹方字体就是正常的，初步怀疑是字体原因，明天我再具体排查一下〜

好的 谢谢
