### ISSUE TITLE
如何把滑动的文字换成图片

### ISSUE THREAD

**Issue by azxcffdgadf** [zyyoona7/WheelPicker#14]
如何把滑动的文字换成图片

**Comment by zyyoona7** [comment]
换乘图片的意思是 滚轮图片选择？

**Comment by azxcffdgadf** [comment]
是的

**Comment by zyyoona7** [comment]
那样的话，这个库不支持的，图片毕竟比较大，可能需要 ViewGroup 来实现，而这个是通过自定义 View 实现的，建议你可以考虑 RecyclerView 的方式实现，搜一下应该挺多的~
