### ISSUE TITLE
提个建议，datepicker 隐藏某一项的时候，datepicker 能自动铺满

### ISSUE THREAD

**Issue by hahagod** [zyyoona7/WheelPicker#17]
如下图：

![QQ图片20190709181831](https://user-images.githubusercontent.com/11895727/60880314-07126f00-a276-11e9-884c-5e8280678528.png)

**Comment by zyyoona7** [comment]
1.0.8 版已经增加了自定义 DatePickerView 的功能，欢迎尝试~对包结构有小的调整，还请先查看一下更新日志~
