### ISSUE TITLE
OnWheelChangedListener 回调BUG

### ISSUE THREAD

**Issue by fairytale110** [zyyoona7/WheelPicker#2]
问题1：
使用场景，滑动wheel选择数据，如果滑动未停止，或者未选中，禁用外部某个控件。
当我触摸Wheel滚动到我需要的position到中间选中那个Viwe时，这时手指再离开屏幕，onWheelSelected未执行，OnItemSelectedListener也未进入回调，但是这时getSelectedItemPosition是选中有正确结果的。
这时我只有进入onWheelScrollStateChanged方法判断state是否为SCROLL_STATE_IDLE来确定wheel停止了滚动，

问题2：
 item textSize 设置同一个值，在Android 5.0及以上和在 5.0一下，显示效果不一样，在5.0以下，显示的item字体变得很大，测试设备为Android SDK X86模拟器

**Comment by zyyoona7** [comment]
感谢反馈~
**关于问题1：** 在 WheelView 中 OnWheelChangedListener 的 onWheelSelected() 方法和 OnItemSelectedListener 的 onItemSelected() 方法回调时机是一样的，并且回调机制类似于 ViewPager 的 onPageSelected() 方法，即只有 item 滚动停止选中或 setSelectedItemPosition() 的时候才会回调一次，如果手指触摸改变了滚动状态但是选中的 item 没有变化的时候是不会执行回调的~所以滚动状态的需要根据 onWheelScrollStateChanged() 方法回调进行判断。

**关于问题2：** 我拿手机测试了一下，这种情况和系统版本没有关系，是不同屏幕分辨率造成的，字体大小一样的普通 TextView 在分辨率低的手机上看也会稍大一些。

_假设同样的 24dp_
**设备 A** 屏幕宽度 1080px，density 2.625，24dp 转换后为 63px，在屏幕上占比 63/1080=0.0583。 
**设备 B** 屏幕宽度 768px，density 2.0，24dp 转换后为 48px，在屏幕上占比 48/768=0.0625。
相同尺寸在低分辨率手机上显示屏幕占比更大些。 具体换算可以看下这篇文章[骚年你的屏幕适配方式该升级了!-今日头条适配方案](https://juejin.im/post/5b7a29736fb9a019d53e7ee2)
