### ISSUE TITLE
在给控件设置一个  size为0的list时会出现java.lang.ArithmeticException  divide by zero

### ISSUE THREAD

**Issue by tao111222333444** [zyyoona7/WheelPicker#21]
在给控件设置一个  size为0的list时会出现java.lang.ArithmeticException  divide by zero 错误    #20 

我觉得这里应该加一个  是否大于0的判断

**Comment by zyyoona7** [comment]
这个已经在最新的代码中修复了，只是还没发布新版~在考虑加点东西再发布

**Comment by tao111222333444** [comment]
哦哦哦   已经修复了
