### ISSUE TITLE
数组越界的错误 多次setdata出现的

### ISSUE THREAD

**Issue by doumingliangdegithub** [zyyoona7/WheelPicker#28]
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
    at java.util.ArrayList.get(ArrayList.java:439)
    at com.zyyoona7.wheel.WheelView.run(WheelView.java:1144)

**Comment by zyyoona7** [comment]
请问是什么版本的？

**Comment by doumingliangdegithub** [comment]
implementation 'com.github.zyyoona7:wheelview:1.0.7'

**Comment by zyyoona7** [comment]
看了下代码确实有可能造成这种问题，如果书写正确是否还有此问题呢？如果有我这边再测试一下~最近一直在搞 2.0 版本

**Comment by doumingliangdegithub** [comment]
你说的书写正确是指 只setData一次吗？如果一次，没有问题。希望您的2.0版本尽快推出，也希望对这个问题加一个解决办法，因为我的业务会多次调用这个setData方法.

**Comment by zyyoona7** [comment]
可以详细说明一下场景么？我这边测试连续多次 setData() 没有崩溃~或者你上一下代码？

**Comment by zyyoona7** [comment]
没有收到后续反馈，先关掉了，如果还有问题，请再打开~

**Comment by doumingliangdegithub** [comment]
好的，感谢你贡献的代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zyyoona7"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 下午5:20
收件人: "zyyoona7/WheelPicker"<WheelPicker@noreply.github.com&gt;; 
抄送: "老和尚"<505738005@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zyyoona7/WheelPicker] 数组越界的错误 多次setdata出现的 (#28)





 
没有收到后续反馈，先关掉了，如果还有问题，请再打开~
