### ISSUE TITLE
快速上下滑动不灵敏

### ISSUE THREAD

**Issue by hellowwwwp** [zyyoona7/WheelPicker#32]
在 onTouchEvent 的 按下时, 应该重置快速滑动标记位
isFlingScroll = false;
本来打算提 PR, 但是没有权限, 分支推不上去

**Comment by zyyoona7** [comment]
1.x 还是 2.x，我抽时间改一下

**Comment by zyyoona7** [comment]
@wp292519413 已在 2.0.1 版本修复了快速滚动的问题，欢迎下载尝试 在 2.x 分支
