### ISSUE TITLE
setSelectedItemPosition在position为0的时候不回调setOnItemSelectedListener

### ISSUE THREAD

**Issue by oOJohn6Oo** [zyyoona7/WheelPicker#34]
是这样的，我有一个三级联动的列表

比如 `地区列表，学校列表，班级列表`

理想做法是
给学校列表对应的WheelView设置`setOnItemSelectedListener`，在listener内部设置班级列表的data，地区选择改变后，我学校列表重新setData，再调一下`setSelectedItemPosition(position)`就行了。

但是我发现这个`calculateItemDistance`计算Item之间差值的方法，在position为0的时候是0

```
int itemDistance = calculateItemDistance(position);
if (itemDistance == 0) {
    return;
}
```

这地方就直接返回了。
导致调用不了。
希望能解决这个问题，或者说有其他方式？

按理讲三级联动，我是可以在第一级ItemSelected和第二级ItemSelected的监听中都重新设置第三级的data，但是显得很笨。

**Comment by zyyoona7** [comment]
你是用的 1.x 版本的吧，2.x 已经修复了这个问题，但是 2.x 版本改动比较大，最近一直太忙 2.x 的文档还没写，我今天修复下 1.x 的这个问题吧

**Comment by oOJohn6Oo** [comment]
> 你是用的 1.x 版本的吧，2.x 已经修复了这个问题，但是 2.x 版本改动比较大，最近一直太忙 2.x 的文档还没写，我今天修复下 1.x 的这个问题吧

嗯，我用的1.0.7，2.x我没关注，没敢用，还是坐等更新吧，不着急😀😁😀

**Comment by zyyoona7** [comment]
升级到 1.0.8 试一下，这个问题已经在 1.x 分支上修复了，没有合并到 master
