### ISSUE TITLE
一个优化建议

### ISSUE THREAD

**Issue by hellowwwwp** [zyyoona7/WheelPicker#35]
WheelView 在滚动状态时调用 getSelectedItemPosition(), 会发现返回的值和用户看到的不一致. 建议在这个方法中, 先判断是否在滚动, 如果在滚动就返回 getCurrentPosition(), 否则返回 mSelectedItemPosition. getSelectedItemData() 同理.

**Comment by zyyoona7** [comment]
1.x 版本的吗？

**Comment by hellowwwwp** [comment]
1.x 和 2.x 都试过, 同样都会存在.

**Comment by zyyoona7** [comment]
感谢反馈，已经在 2.0.2 版本修复此问题~欢迎体验
