### ISSUE TITLE
DatePicker 设置完日期#setYearRange()后更新updateMaxAndMinYear()的逻辑有问题。

### ISSUE THREAD

**Issue by eurigo** [zyyoona7/WheelPicker#36]
会导致选择年份自动跳转到最小年份

**Comment by zyyoona7** [comment]
设置的当前选中时间是否小于 最小/最大 范围？

**Comment by eurigo** [comment]
没有。
比如代码如下，只设置年份区间
yearWv3.setYearRange(2018, 2020);

没有再另外设置最小年份，滑动后默认会跳回最小的2018这个年份

**Comment by zyyoona7** [comment]
多少版本 1.x ? 还是 2.x ?

**Comment by eurigo** [comment]
没看有2.x呀，引入的是
implementation  com.github.zyyoona7:pickerview:1.0.9

**Comment by zyyoona7** [comment]
这个问题还存在吗？如果还存在麻烦贴一下调用代码重新打开~
