### ISSUE TITLE
大佬DatePickerView可以设置年月日时分秒格式么...

### ISSUE THREAD

**Issue by 15620879530** [zyyoona7/WheelPicker#37]

**Comment by zyyoona7** [comment]
1.x 版本没有，2.x 有 DatePicker 和 TimePicker 可以组合使用

**Comment by 15620879530** [comment]
> 1.x 版本没有，2.x 有 DatePicker 和 TimePicker 可以组合使用

好的好的 我在看看 谢谢分享啊！！
