### ISSUE TITLE
DatePickerView match_parent view 显示不正确

### ISSUE THREAD

**Issue by wilder-ness** [zyyoona7/WheelPicker#4]
DatePickerView match_parent view 显示不正确只是父级view 变宽了
![image](https://user-images.githubusercontent.com/16201257/48471415-d422f300-e82e-11e8-8307-04cbdfdc323e.png)
 子view并没有一起变化

**Comment by zyyoona7** [comment]
是的，因为在 DatePickerView 的布局中写死了 wrap_content，大多数日期选择都是居中的，可以通过字体大小等属性去控制样式。

**Comment by wilder-ness** [comment]
这个我自己自定义了个父级搞定了。
因为我还要又有要yyyy-MM-dd HH:mm 的选项。
我觉得可以暴露一个子项view 的宽度的设置比较好点。 因为字体大小毕竟有UI 的要求。
不过还是要感谢你分享这个库。其他的滚轮选择我看了许多 对滚轮view 的控制都没你的好 虽然用的人很多。但是只是封装的其他的 一些东西。感觉再滚轮view的控制上不怎么样。。只是照搬了别人的库

**Comment by zyyoona7** [comment]
感谢你提供建议，当时写 DatePickerView 的时候考虑到了年月日时分秒的情况，而且情况比较多，比如只需要时分秒或者只需要年月之类的，所以没有去适配时分秒，只写了年月日的选择。

我建议你可以参照 DatePickerView 的写法自己在项目里实现一套自己的年月日时分的 DatePickerView，时分两个也比较好实现，小时的 WheelView 为固定的 0-23 或 12 小时制，分钟的 WheelView 为固定的 0-59。需求明确写起来也比较容易~

**Comment by wilder-ness** [comment]
我就是按照你的YearWheelView 写的。 已经完成。3q

**Comment by zyyoona7** [comment]
👍

**Comment by LOWANGA** [comment]
我也是这样

**Comment by zyyoona7** [comment]
@LOWANGA 有同样的需求可以按照上面说的自己实现~
