### ISSUE TITLE
Out-projected type 'WheelView<*>!' prohibits the use of 'public open fun setOnItemSelectedListener(onItemSelectedListener: WheelView.OnItemSelectedListener<T!>!): Unit defined in com.zyyoona7.wheel.WheelView'

### ISSUE THREAD

**Issue by HJJKnight** [zyyoona7/WheelPicker#40]
`mLoopView.setOnItemSelectedListener(WheelView.OnItemSelectedListener<String> { wheelView, data, position ->
 })`
在kotlin 中给WheelView设置OnItemSelectedListener时报错，错误提示：
Out-projected type 'WheelView<*>!' prohibits the use of 'public open fun setOnItemSelectedListener(onItemSelectedListener: WheelView.OnItemSelectedListener<T!>!): Unit defined in com.zyyoona7.wheel.WheelView'

**Comment by zyyoona7** [comment]
```kotlin
    fun setOnItemSelectedListener(itemSelectedListener: OnItemSelectedListener?) {
        this.itemSelectedListener = itemSelectedListener
    }
```
这个方法使用不需要传泛型的
```kotlin
mLoopView.setOnItemSelectedListener(WheelView.OnItemSelectedListener<String> { wheelView, data, position -> })
```
这块设置的方法应该不对，可以参考一下 Demo。

**Comment by HJJKnight** [comment]
> ```kotlin
>     fun setOnItemSelectedListener(itemSelectedListener: OnItemSelectedListener?) {
>         this.itemSelectedListener = itemSelectedListener
>     }
> ```
> 
> 这个方法使用不需要传泛型的
> 
> ```kotlin
> mLoopView.setOnItemSelectedListener(WheelView.OnItemSelectedListener<String> { wheelView, data, position -> })
> ```
> 
> 这块设置的方法应该不对，可以参考一下 Demo。

好的，我再看一下
