### ISSUE TITLE
Setting custom Font from assets (Wheel View)

### ISSUE THREAD

**Issue by HuM4NoiD** [zyyoona7/WheelPicker#43]
How do I set custom font from otf/ttf files in assets folder?

**Comment by Prashantjagwani** [comment]
You can use the methods below from the library.
public void setTypeface(Typeface typeface, boolean isBoldForSelectedItem)

Here is how i did it
`val wheelView = v.findViewById<WheelView<String>>(R.id.wheelview) //pass id of your custom wheelview in the bracket`
`//Below is part for custom font`
`wheelView.setTypeface(
            Typeface.createFromAsset(
                applicationContext.assets,
                "fonts/name_of_your_font.ttf"
            ), false
        )`
