### ISSUE TITLE
滚轮文字不可见，但是可滑动，有回调

### ISSUE THREAD

**Issue by Nstd** [zyyoona7/WheelPicker#44]
目前使用的是1.0.9的版本
debug了一下，布局重复测量的时候，在 `onMeasure()` 里 `realWidth` 可能为0。导致 `mMaxTextWidth` 变成了0，文字显示不出来。
回退到1.0.8就正常了
https://github.com/zyyoona7/WheelPicker/blob/d1c3f71aa53947b105852d85e62238c71f95a114/wheelview/src/main/java/com/zyyoona7/wheel/WheelView.java#L369-L385

**Comment by amosxb** [comment]
想问下这个只是回退就好了么，有解决办法么？

**Comment by Nstd** [comment]
> 想问下这个只是回退就好了么，有解决办法么？

@amosxb 作者已经很久没更新了，可以比较下两个版本的差异，自己fork进行fix

**Comment by amosxb** [comment]
> > 想问下这个只是回退就好了么，有解决办法么？
> 
> @amosxb 作者已经很久没更新了，可以比较下两个版本的差异，自己fork进行fix

问下，你那边有1.0.8版本的地址么？

**Comment by Nstd** [comment]
> 问下，你那边有1.0.8版本的地址么？

你把版本号改一下就好了吧。我当时没用2.x的版本，你可以试试2.x的

**Comment by amosxb** [comment]
> 
我用的就是2.x的版本，回退到1.0.8根本不行，代码改的太多了。好多类在1.0.8都没了。

**Comment by zyyoona7** [comment]
仓库已切换到 jitpack
```groovy
allprojects {
        repositories {
            //...
            maven { url 'https://jitpack.io' }
	}
}
```
请升级到最新依赖：
1.x版本
```groovy
    dependencies {
        implementation 'com.github.zyyoona7.WheelPicker:pickerview:1.1.2'
        //或
        implementation 'com.github.zyyoona7.WheelPicker:wheelview:1.1.2'
    }
```
2.x版本
```groovy
    dependencies {
        implementation 'com.github.zyyoona7.WheelPicker:pickerview:2.0.7'
        //或
        implementation 'com.github.zyyoona7.WheelPicker:wheelview:2.0.7'
    }
```
