### ISSUE TITLE
条目少的时候,会把内容滚消失

### ISSUE THREAD

**Issue by lcz1688** [zyyoona7/WheelPicker#7]
![screenshot_20190122-110502](https://user-images.githubusercontent.com/29850408/51509859-add49180-1e35-11e9-961d-6c3ce631e19f.jpg)
我只有三个条目,当上方或者下方有空白条目时,点空白处,会计算滚动.多次点击,内容会消失
  int clickToCenterDistance = 0;
                    if (System.currentTimeMillis() - mDownStartTime <= DEFAULT_CLICK_CONFIRM) {
                        //处理点击滚动
                        //手指抬起的位置到中心的距离为滚动差值
                        clickToCenterDistance = (int) (event.getY() - mCenterY);
                    }
你这里是无限上滚或者下滚的.我没想到怎么处理,只好注释了
//   clickToCenterDistance = (int) (event.getY() - mCenterY);,这样就去掉了点击事件
.版主试试看怎么解决下,谢谢

**Comment by lcz1688** [comment]
![screenshot_20190122-110457](https://user-images.githubusercontent.com/29850408/51510073-8d590700-1e36-11e9-9859-40f3689b7011.jpg)

**Comment by zyyoona7** [comment]
好的，我记录一下~尽快修复

**Comment by zyyoona7** [comment]
已经修复~欢迎下载最新版体验
