### ISSUE TITLE
滑动 选中失效

### ISSUE THREAD

**Issue by LOWANGA** [zyyoona7/WheelPicker#8]
滑动 选中失效

部分机型 还是会偶尔出现滑动到某一项 点击确定按钮 取值不是滑动的那一项  是原来的选中数据

**Comment by zyyoona7** [comment]
你好，请问尝试[这种](https://github.com/zyyoona7/WheelPicker/issues/5#issuecomment-451103648)解决方法了吗？

**Comment by LOWANGA** [comment]
更新了最新版本 但是没有记录滑动状态

**Comment by zyyoona7** [comment]
更新了滚动监听，欢迎更新 1.0.7 版本
