### ISSUE TITLE
滑动卡顿

### ISSUE THREAD

**Issue by lvtanxi** [zyyoona7/WheelPicker#9]
在Dialog中，第一次初始化弹出，快速的去滑动，这时候整个条目是卡顿的，没有滑动效果

**Comment by zyyoona7** [comment]
你好，请问是什么机型？还是全部都是这个样子？可否贴一下代码

**Comment by lvtanxi** [comment]
三星note4；这个机器全部都是这样。
`
import android.support.v4.app.FragmentManager;
import android.view.Gravity;
import android.view.View;
import android.widget.TextView;

import com.wm.wmcommon.R;
import com.wumart.lib.base.BaseDialog;
import com.wumart.lib.common.ArrayUtils;
import com.zyyoona7.wheel.WheelView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * Date: 2016-09-05
 * Time: 13:30
 * Description:
 */
public class WheelChooseDialog<T extends WheelChooseDialog.SingleWheelChooseItem> extends BaseDialog {
    private WheelView mSingleWheelView;
    private View mChooseCancel;
    private View mChooseConfirm;
    private TextView mChooseTitle;
    private OnChooseListener<T> mOnChooseListener;
    private List<T> mDatas;
    private String mTitleStr;
    private boolean cyclic=false;


    @Override
    protected int loadLayoutId() {
        mGravity = Gravity.BOTTOM;
        return R.layout.view_single_wheel_choose_dialog;
    }


    @Override
    protected void bindListener() {
        super.bindListener();
        bindClickListener(mChooseCancel, mChooseConfirm);
    }

    @Override
    protected void initData() {
        mChooseTitle.setText(mTitleStr);
        mSingleWheelView.setCyclic(cyclic);
        if (ArrayUtils.isEmpty(mDatas))
            mDatas = new ArrayList<>(0);
        bindData();
    }

    private void bindData() {
        if (null != mSingleWheelView){
            List<String> data=new ArrayList<>();
            for (T t : mDatas) {
                data.add(t.obtainItemStr());
            }
            mSingleWheelView.setData(data);
        }
    }

    public WheelChooseDialog<T> setTitle(String titleStr) {
        mTitleStr = titleStr;
        return this;
    }

    public WheelChooseDialog<T> setCyclic(boolean cyclic) {
        this.cyclic = cyclic;
        return this;
    }

    public WheelChooseDialog<T> bindData(List<T> datas) {
        mDatas = datas;
        bindData();
        return this;
    }

    public WheelChooseDialog<T> bindChooseListener(OnChooseListener<T> onChooseListener) {
        mOnChooseListener = onChooseListener;
        return this;
    }

    public void showDialog(FragmentManager manager, String tag) {
        if (dataIsEmpty())
            return;
        show(manager, tag);
    }


    @Override
    protected void onClick(View view, int id) {
        if (id == R.id.choose_confirm && mOnChooseListener != null && !dataIsEmpty()) {
           int mLastItem = mSingleWheelView.getSelectedItemPosition();
            mOnChooseListener.onChoose(mDatas.get(mLastItem));
        }
        dismiss();
    }

    public interface SingleWheelChooseItem {
        String obtainItemStr();
    }

    public interface OnChooseListener<T extends SingleWheelChooseItem> {
        void onChoose(T t);
    }

    public boolean dataIsEmpty() {
        return ArrayUtils.isEmpty(mDatas);
    }
}

`

**Comment by zyyoona7** [comment]
好的，感谢，我晚上回去试一下~

**Comment by zyyoona7** [comment]
腾讯云真机上没有这个机型，我在 [demo](https://github.com/zyyoona7/WheelPicker/blob/master/app/src/main/java/com/zyyoona7/demo/CityPickerDialogFragment.java) 里面新增了一个弹窗的示例，可否试一下？

**Comment by lvtanxi** [comment]
还是一样的

**Comment by zyyoona7** [comment]
系统版本是多少的

**Comment by lvtanxi** [comment]
5.1.1

**Comment by zyyoona7** [comment]
升级到最新版再观察一下~如果还卡顿再打开 issue
